### ISSUE TITLE
Implement the primitives that cause the "make ut-js" unit tests to fail

### ISSUE THREAD

**Issue by feeley** [gambit/gambit#232]
Estimated time: 20 hours

A ```make ut-js``` has many failed unit tests, for example:

```
% make ut-js
[ 51|  0]  35% #####........... 57.3s 01-fixnum/fxwraparithmetic-shift-left.scm
/Users/feeley/gambit/work/tests/_test.exe:1971
   return g_peps["##fxwraparithmetic-shift-left?"]();
                                                  ^

TypeError: g_peps.##fxwraparithmetic-shift-left? is not a function
   at g_bb27__20_fxwraparithmetic_2d_shift_2d_left (/Users/feeley/gambit/work/tests/_test.exe:1971:52)
   at g_bb24__20_fxwraparithmetic_2d_shift_2d_left (/Users/feeley/gambit/work/tests/_test.exe:1916:14)
   at g_trampoline (/Users/feeley/gambit/work/tests/_test.exe:194:10)
   at g_module_register (/Users/feeley/gambit/work/tests/_test.exe:837:9)
   at Object.<anonymous> (/Users/feeley/gambit/work/tests/_test.exe:597495:1)
   at Module._compile (module.js:413:34)
   at Object.Module._extensions..js (module.js:422:10)
   at Module.load (module.js:357:32)
   at Function.Module._load (module.js:314:12)
   at Function.Module.runMain (module.js:447:10)

*** FAILED 01-fixnum/fxwraparithmetic-shift-left.scm WITH EXIT CODE HI=1 LO=0
```

This failure is caused by the missing implementation of the
```##fxwraparithmetic-shift-left?``` primitive.

Note that a compiler unit test for this primitive should be added
as ```gsc/tests/03-fxprim/fxwrapaslp.scm```.

**Comment by feeley** [comment]
Here are some notes in french on how to fix address this issue...

Pour comprendre le problème quelques infos utiles...

Le tableau ```g_peps``` contient les "primitive entry points".  Note : le ```g_``` c'est le préfixe aux noms des variables globales "Gambit", et le préfixe ```G_``` c'est pour les classes globales "Gambit".

L'erreur provient du fait que la primitive ```##fxwraparithmetic-shift-left?``` n'est pas implantée par le backend JS.  En principe ```g_peps["##fxwraparithmetic-shift-left?"]``` devrait contenir la fonction JS qui correspond au point d'entrée de la fonction Scheme ```##fxwraparithmetic-shift-left?```, mais c'est en fait ```undefined```.

Petite parenthèse... Quel est le comportement attendu de la fonction ```##fxwraparithmetic-shift-left?```?  Elle prend 2 paramètres fixnums, x et y, et retourne ```#f``` si y<0 ou y>"fixnum width", sinon calcule ```x<<y``` tronqué aux bits significatifs d'un fixnum (les bits supérieurs sont perdus).

Mais pourquoi cette primitive est-elle appelée puisque le fichier tests/unit-tests/01-fixnum/fxwraparithmetic-shift-left.scm ne semble pas contenir d'appel à cette primitive?

Il faut comprendre que le compilateur gsc va faire une expansion inline de la primitive fxwraparithmetic-shift-left (sans point d'interrogation) pour que ce soit plus performant (pour ne pas faire d'appel de fonction Scheme dans le "fast path").

La ligne suivante du fichier de test :

```
(check-eqv? (fxwraparithmetic-shift-left -5 5) -160)
```

sera expansé en :

```
(let (($actual-result$
       (if ('#<procedure #2 ##eq?>
            fxwraparithmetic-shift-left
            '#<procedure #23 fxwraparithmetic-shift-left>)
           (or ('#<procedure #24 ##fxwraparithmetic-shift-left?> -5 5)
               (fxwraparithmetic-shift-left -5 5))
           (fxwraparithmetic-shift-left -5 5))))
  (if (##eqv? $actual-result$ -160)
      #f
      (##failed-check "\"tests/unit-tests/01-fixnum/fxwraparithmetic-shift-left.scm\"@12.1: FAILED (check-eqv? (fxwraparithmetic-shift-left -5 5) -160)" $actual-result$)))
```

La partie importante c'est que l'appel ```(fxwraparithmetic-shift-left -5 5)``` est remplacé par :

```
       (if ('#<procedure #2 ##eq?>
            fxwraparithmetic-shift-left
            '#<procedure #23 fxwraparithmetic-shift-left>)
           (or ('#<procedure #24 ##fxwraparithmetic-shift-left?> -5 5)
               (fxwraparithmetic-shift-left -5 5))
           (fxwraparithmetic-shift-left -5 5))
```

Et le coeur de ça c'est :

```
           (or ('#<procedure #24 ##fxwraparithmetic-shift-left?> -5 5)
               (fxwraparithmetic-shift-left -5 5))
```

qui va essayer de faire le calcul "inline" avec la primitive ```##fxwraparithmetic-shift-left?``` et si cela échoue (valeur de retour ```#f```) un véritable appel sera fait à la fonction ```fxwraparithmetic-shift-left``` qui se chargera, si c'était le cas, de lever une exception indiquant que le deuxième paramètre est "out of range".

Pour obtenir l'expansion on aurait pu faire :

```
% gsc/gsc -:=. -target js -c -expansion tests/unit-tests/01-fixnum/fxwraparithmetic-shift-left.scm
```

mais celà ne fonctionne pas dans ce cas précis, car le pretty-printer de l'expansion de code suppose que la fonction ```##fxwraparithmetic-shift-left?``` est définie (pour bien afficher le nom de la fonction), mais hélas cette définition est en commentaire dans le fichier ```lib/_num.scm``` :

```
;;TODO:enable after bootstrap
;;(define-prim (##fxwraparithmetic-shift-left? x y))
```

Donc pour obtenir l'expansion, il faut soit enlever le commentaire et recompiler Gambit ou bien contourner le problème en donnant une définition bidon de cette fonction (tout ce qui importe c'est qu'une fonction existe sous ce nom) :

```
% gsc/gsc -:=. -target js -c -expansion -e "(define (##fxwraparithmetic-shift-left? x y) 999)" tests/unit-tests/01-fixnum/fxwraparithmetic-shift-left.scm
...
(let (($actual-result$
       (if ('#<procedure #2 ##eq?>
            fxwraparithmetic-shift-left
            '#<procedure #23 fxwraparithmetic-shift-left>)
           (let ((temp.39 ('#<procedure #24 ##fxwraparithmetic-shift-left?>
                           -5
                           5)))
             (if temp.39 temp.39 (fxwraparithmetic-shift-left -5 5)))
           (fxwraparithmetic-shift-left -5 5))))
  (if (##eqv? $actual-result$ -160)
      #f
      (##failed-check
       "\"tests/unit-tests/01-fixnum/fxwraparithmetic-shift-left.scm\"@12.1: FAILED (check-eqv? (fxwraparithmetic-shift-left -5 5) -160)"
       $actual-result$)))
...
```

En ce qui concerne l'implantation des primitives, le fichier ```gsc/_prims.scm``` joue un rôle important. On y trouve la liste des primitives de Gambit, les règles d'expansion, de spécialisation, de constant folding, etc.  On retrouve entre autre les lignes :

```
   (def-exp "fxwraparithmetic-shift-left"
     (make-simple-expander case-fxwraparithmetic-shift-left))
```

qui disent que l'expansion d'un appel à fxwraparithmetic-shift-left se fait par la fonction case-fxwraparithmetic-shift-left dont la définition est :

```
   (define case-fxwraparithmetic-shift-left
     (gen-fixnum-case
      (make-conditional-fixed-arity-generator
       **fxwraparithmetic-shift-left?-sym)))
```

Cette définition dit que les paramètres de la primitive sont des fixnums, et qu'il faut inliner un appel à la primitive ```##fxwraparithmetic-shift-left?``` avant l'appel réel à ```fxwraparithmetic-shift-left```, comme dans le code :

```
           (let ((temp.39 ('#<procedure #24 ##fxwraparithmetic-shift-left?>
                           -5
                           5)))
             (if temp.39 temp.39 (fxwraparithmetic-shift-left -5 5)))
```

Alors où est le problème? En fait si on regarde les fichiers ```gsc/_t-univ-[1234].scm``` on voit qu'il n'y a pas d'implantation de l'inlining de la primitive ```##fxwraparithmetic-shift-left?```.  Il y a cependant la primitive ```##fxarithmetic-shift-left?``` très similaire qui est implantée dans ```gsc/_t-univ-4.scm``` (elle est plus complexe car elle doit retourner ```#f``` si le résultat déborde d'un fixnum).  Mais on peut s'en inspirer :

```
(univ-define-prim "##fxarithmetic-shift-left?" #f
 (make-translated-operand-generator
  (lambda (ctx return arg1 arg2)
    (^if (^< (^fixnum-unbox arg2) (^int 0))
         (return (^obj #f))
         (^
           (^assign (^rts-field-use 'inttemp1)
                    (^if-expr (^> (^fixnum-unbox arg2)
                                  (^int (- univ-word-bits univ-tag-bits)))
                              (^int (- univ-word-bits univ-tag-bits))
                              (^fixnum-unbox arg2)))

           (^assign (^rts-field-use 'inttemp2)
                    (^<< (^fixnum-unbox arg1)
                         (^rts-field-use 'inttemp1)))

           (return (^if-expr (^= (^>> (univ-wrap ctx (^rts-field-use 'inttemp2))
                                      (^rts-field-use 'inttemp1))
                                 (^fixnum-unbox arg1))
                             (^fixnum-box (^rts-field-use 'inttemp2))
                             (^obj #f))))))))
```

pour obtenir cette définition du générateur de code de ```##fxwraparithmetic-shift-left?``` :

```
(univ-define-prim "##fxwraparithmetic-shift-left?" #f
 (make-translated-operand-generator
  (lambda (ctx return arg1 arg2)
    (return
     (^if-expr (^or (^< (^fixnum-unbox arg2)
                        (^int 0))
                    (^> (^fixnum-unbox arg2)
                        (^int (- univ-word-bits univ-tag-bits))))
               (^obj #f)
               (univ-wrap ctx
                          (^<< (^fixnum-unbox arg1)
                               (^fixnum-unbox arg2))))))))
```

À remarquer que chaque forme préfixée de "^" est un générateur de code cible "générique".  Par exemple, ```(^if-expr A B C)``` génère ```A?B:C``` en JavaScript, Java, Ruby et PHP, mais ```B if A else C``` en Python.  Ces formes sont définies comme des macros dans ```gsc/_univadt.scm``` et l'expansion de la macro fait appel à des fonctions dans ```gsc/_t-univ-1.scm```, par exemple :

```
;; dans gsc/_univadt.scm

(define-macro (^if-expr expr1 expr2 expr3)
 `(univ-emit-if-expr ctx ,expr1 ,expr2 ,expr3))
```

```
;; dans gsc/_t-univ-1.scm

(define (univ-emit-if-expr ctx expr1 expr2 expr3)
 (case (target-name (ctx-target ctx))

   ((js ruby java)
    (^ expr1 " ? " expr2 " : " expr3))

   ((php)
    (^parens (^ expr1 " ? " expr2 " : " expr3)))

   ((python)
    (^ expr2 " if " expr1 " else " expr3))

   (else
    (compiler-internal-error
     "univ-emit-if-expr, unknown target"))))
```

La forme ```(^ A B C)``` est essentiellement un "append intelligent" des codes A, B et C.  La forme ```(^int N)``` génère la constante entière N.  La forme ```(^obj X)``` génère la constante Scheme X.  La forme ```(^fixnum-unbox X)``` donne le code qui extrait la valeur numérique du fixnum X.  L’appel ```(univ-wrap ctx expr)``` donne le code qui tronque la valeur de l’expression numérique “expr” pour que ça “fit” dans un fixnum.

Il faut donc...

1) réparer le bug avec ```##fxwraparithmetic-shift-left?```, ce qui va demander de faire l'ajout de ```(univ-define-prim "##fxwraparithmetic-shift-left?" #f ...)``` à ```gsc/_t-univ-4.scm``` et dans ```lib/_num.scm``` enlever le commentaire autour de ```(define-prim (##fxwraparithmetic-shift-left? x y))``` .

2) ajouter un unit test de cette primitive (on peux s'inspirer de ```tests/unit-tests/01-fixnum/fxarithmetic-shift-leftp.scm``` et ```tests/unit-tests/01-fixnum/fxwraplogical-shift-rightp.scm``` pour créer ```tests/unit-tests/01-fixnum/fxwraplogical-shift-leftp.scm```).

3) ajouter un unit test de ```##fxwraparithmetic-shift-left?``` aux unit tests du compilateur dans ```gsc/tests/03-fxprim/fxwrapaslp.scm```.

**Comment by 316k** [comment]
A few unit tests still fail due to primitives (see #261).

Not all tests pass, there's the generalized :

    "unit-tests/07-vector/u16vector.scm"@336.1: FAILED (check-tail-exn type-exception? (lambda () (u16vector-set! v5 0 65536))) GOT #!void

along with all the thread-related tests, serialization and port-related tests, but these are all different issues.
