### ISSUE TITLE
"Errors" caught by gcc's sanitizers

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#738]
I configured Gambit with
```
 ./configure 'CC=/usr/local/gcc-11.2.0/bin/gcc -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment -ldl' --enable-single-host --enable-debug
```
The `-ldl` was needed to fix the following:
```
/usr/local/gcc-11.2.0/bin/gcc -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment -Wno-unused -Wno-write-strings -Wdisabled-optimization -g -ftrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -foptimize-sibling-calls -fPIC -fno-common -mpc64   -rdynamic  -I"../include"  -o gsi    _gsi.o _gsi_.o "../lib/libgambit.a" -lutil -lm  libgambitgsi.a
/usr/bin/ld: ../lib/libgambit.a(os_dyn.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I immediately hit
```
heine:~/programs/gambit/gambit> gsi/gsi
mem.c:5485:3: runtime error: left shift of 140210907573497 by 62 places cannot be represented in type 'long int'
```
So maybe that's too much "sanitizing" going on, so I'll try to dial it back a bit, but it would be good if we could get a clean compile and run.

**Comment by gambiteer** [comment]
Here is something that gave me a smile:  Virtual memory is reported as 20TB (with a "T"!):
```
lucier    306977 81.8  1.4 21474998824 487288 pts/0 R+ 12:39   1:59 /home/lucier/programs/gambit/gambit/gsi/gsi
```

**Comment by gambiteer** [comment]
Here's a problem:
```
Starting program: /home/lucier/programs/gambit/gambit/gsi/gsi 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Gambit v4.9.4-16-g05b050f8

> (define (partial-factorial m n)
  ;; computes the product (m+1) * ... * (n-1) * n
  (if (< (- n m) 10)
      (apply * (iota (+ m 1) (+ n 1)))
      (* (partial-factorial m (quotient (+ m n) 2))
         (partial-factorial (quotient (+ m n) 2) n))))
> (define a (time (partial-factorial 1 6000)))    

Program received signal SIGCONT, Continued.
0x00007ffff768731b in __asan::__asan_store4 (addr=<optimized out>) at ../../../../src/libsanitizer/asan/asan_rtl.cpp:189
189	../../../../src/libsanitizer/asan/asan_rtl.cpp: No such file or directory.
(gdb) fg
Continuing.
(time (partial-factorial 1 6000))
    147.008454 secs real time
    140.017582 secs cpu time (138.845610 user, 1.171972 system)
    2624 collections accounting for 2.986140 secs real time (2.748741 user, 0.223006 system)
    3056259528 bytes allocated
    982357 minor faults
    no major faults
> (define a (time (partial-factorial 1 7000)))
=================================================================
==306977==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7ffff31b3820 at pc 0x00000064b9fc bp 0x7fffffff8390 sp 0x7fffffff8380
WRITE of size 8 at 0x7ffff31b3820 thread T0
    #0 0x64b9fb in ___H___kernel /home/lucier/programs/gambit/gambit/lib/_kernel.c:11044
    #1 0xb3180f in ___H___num /home/lucier/programs/gambit/gambit/lib/_num.c:101791
    #2 0x58eb1c in ___trampoline /home/lucier/programs/gambit/gambit/lib/setup.c:3035
    #3 0x58fb13 in ___call /home/lucier/programs/gambit/gambit/lib/setup.c:3146
    #4 0x5902c0 in ___run /home/lucier/programs/gambit/gambit/lib/setup.c:3186
    #5 0x598d66 in ___setup /home/lucier/programs/gambit/gambit/lib/setup.c:6170
    #6 0x6290ba in ___main /home/lucier/programs/gambit/gambit/lib/main.c:1222
    #7 0x5d37d3 in ___main_char /home/lucier/programs/gambit/gambit/lib/os_base.c:590
    #8 0x586338 in main /home/lucier/programs/gambit/gambit/gsi/_gsi_.c:15882
    #9 0x7ffff693a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x569c0d in _start (/home/lucier/programs/gambit/gambit/gsi/gsi+0x569c0d)

0x7ffff31b3827 is located 0 bytes to the right of 1048615-byte region [0x7ffff30b3800,0x7ffff31b3827)
allocated by thread T0 here:
    #0 0x7ffff767c527 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5d2c85 in ___alloc_mem /home/lucier/programs/gambit/gambit/lib/os_base.c:226
    #2 0x5d2df3 in ___alloc_mem_heap /home/lucier/programs/gambit/gambit/lib/os_base.c:444
    #3 0x598eb6 in alloc_mem_aligned_aux /home/lucier/programs/gambit/gambit/lib/mem.c:563
    #4 0x59905f in alloc_mem_aligned_heap /home/lucier/programs/gambit/gambit/lib/mem.c:611
    #5 0x59a982 in adjust_msections /home/lucier/programs/gambit/gambit/lib/mem.c:967
    #6 0x5a74ee in ___setup_mem_vmstate /home/lucier/programs/gambit/gambit/lib/mem.c:4607
    #7 0x590930 in setup_os_and_mem_vmstate /home/lucier/programs/gambit/gambit/lib/setup.c:4391
    #8 0x5917e0 in ___setup_vmstate /home/lucier/programs/gambit/gambit/lib/setup.c:4596
    #9 0x598a8b in ___setup /home/lucier/programs/gambit/gambit/lib/setup.c:6128
    #10 0x6290ba in ___main /home/lucier/programs/gambit/gambit/lib/main.c:1222
    #11 0x5d37d3 in ___main_char /home/lucier/programs/gambit/gambit/lib/os_base.c:590
    #12 0x586338 in main /home/lucier/programs/gambit/gambit/gsi/_gsi_.c:15882
    #13 0x7ffff693a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lucier/programs/gambit/gambit/lib/_kernel.c:11044 in ___H___kernel
Shadow bytes around the buggy address:
  0x10007e62e6b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007e62e6c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007e62e6d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007e62e6e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007e62e6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007e62e700: 00 00 00 00[07]fa fa fa fa fa fa fa fa fa fa fa
  0x10007e62e710: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x10007e62e720: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x10007e62e730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x10007e62e740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x10007e62e750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==306977==ABORTING
[Inferior 1 (process 306977) exited with code 01]
```
I configured without shift checking:
```
heine:~/programs/gambit/gambit> gsi/gsi -v
v4.9.4-16-g05b050f8 20220210003317 x86_64-pc-linux-gnu "./configure 'CC=/usr/local/gcc-11.2.0/bin/gcc -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment -fno-sanitize=shift -ldl' '--enable-single-host' '--enable-debug'"
```

**Comment by gambiteer** [comment]
I found this page helpful: https://developers.redhat.com/blog/2021/05/05/memory-error-checking-in-c-and-c-comparing-sanitizers-and-valgrind

**Comment by gambiteer** [comment]
You can get the same problem with "only" 6,000 arguments:
```
heine:~/programs/gambit/gambit> gsi/gsi
Gambit v4.9.4-16-g05b050f8

> (define (partial-factorial m n)
  ;; computes the product (m+1) * ... * (n-1) * n
  (if (< (- n m) 10)
      (apply * (iota (+ m 1) (+ n 1)))
      (* (partial-factorial m (quotient (+ m n) 2))
         (partial-factorial (quotient (+ m n) 2) n))))
> (define a (time (partial-factorial 1 6000)))          
(time (partial-factorial 1 6000))
    139.566396 secs real time
    139.377255 secs cpu time (138.178899 user, 1.198356 system)
    2624 collections accounting for 2.944319 secs real time (2.712394 user, 0.228794 system)
    3056259528 bytes allocated
    975676 minor faults
    no major faults
> (define a (time (partial-factorial 1 6000)))
=================================================================
==308364==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f907d9fb828 at pc 0x00000064ba8c bp 0x7ffec1964210 sp 0x7ffec1964200
WRITE of size 8 at 0x7f907d9fb828 thread T0
    #0 0x64ba8b in ___H___kernel /home/lucier/programs/gambit/gambit/lib/_kernel.c:11044
    #1 0xb3180f in ___H___num /home/lucier/programs/gambit/gambit/lib/_num.c:101791
    #2 0x58eb1c in ___trampoline /home/lucier/programs/gambit/gambit/lib/setup.c:3035
    #3 0x58fb13 in ___call /home/lucier/programs/gambit/gambit/lib/setup.c:3146
    #4 0x5902c0 in ___run /home/lucier/programs/gambit/gambit/lib/setup.c:3186
    #5 0x598d66 in ___setup /home/lucier/programs/gambit/gambit/lib/setup.c:6170
    #6 0x6290ba in ___main /home/lucier/programs/gambit/gambit/lib/main.c:1222
    #7 0x5d37d3 in ___main_char /home/lucier/programs/gambit/gambit/lib/os_base.c:590
    #8 0x586338 in main /home/lucier/programs/gambit/gambit/gsi/_gsi_.c:15882
    #9 0x7f908118d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x569c0d in _start (/home/lucier/programs/gambit/gambit/gsi/gsi+0x569c0d)

0x7f907d9fb828 is located 1 bytes to the right of 1048615-byte region [0x7f907d8fb800,0x7f907d9fb827)
allocated by thread T0 here:
    #0 0x7f9081ecf527 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5d2c85 in ___alloc_mem /home/lucier/programs/gambit/gambit/lib/os_base.c:226
    #2 0x5d2df3 in ___alloc_mem_heap /home/lucier/programs/gambit/gambit/lib/os_base.c:444
    #3 0x598eb6 in alloc_mem_aligned_aux /home/lucier/programs/gambit/gambit/lib/mem.c:563
    #4 0x59905f in alloc_mem_aligned_heap /home/lucier/programs/gambit/gambit/lib/mem.c:611
    #5 0x59a982 in adjust_msections /home/lucier/programs/gambit/gambit/lib/mem.c:967
    #6 0x5a74ee in ___setup_mem_vmstate /home/lucier/programs/gambit/gambit/lib/mem.c:4607
    #7 0x590930 in setup_os_and_mem_vmstate /home/lucier/programs/gambit/gambit/lib/setup.c:4391
    #8 0x5917e0 in ___setup_vmstate /home/lucier/programs/gambit/gambit/lib/setup.c:4596
    #9 0x598a8b in ___setup /home/lucier/programs/gambit/gambit/lib/setup.c:6128
    #10 0x6290ba in ___main /home/lucier/programs/gambit/gambit/lib/main.c:1222
    #11 0x5d37d3 in ___main_char /home/lucier/programs/gambit/gambit/lib/os_base.c:590
    #12 0x586338 in main /home/lucier/programs/gambit/gambit/gsi/_gsi_.c:15882
    #13 0x7f908118d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lucier/programs/gambit/gambit/lib/_kernel.c:11044 in ___H___kernel
Shadow bytes around the buggy address:
  0x0ff28fb376b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff28fb376c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff28fb376d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff28fb376e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff28fb376f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff28fb37700: 00 00 00 00 07[fa]fa fa fa fa fa fa fa fa fa fa
  0x0ff28fb37710: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff28fb37720: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff28fb37730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff28fb37740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff28fb37750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==308364==ABORTING
```

**Comment by gambiteer** [comment]
I don't know whether this information is helpful, but I decided to see at what point the program failed.  So I ran an infinite loop with various argument list sizes (killing each one after 40 minutes or so), and found the following:
```
heine:~/programs/gambit/gambit> gsi/gsi
Gambit v4.9.4-16-g05b050f8

> (define (partial-factorial m n)
  ;; computes the product (m+1) * ... * (n-1) * n
  (if (< (- n m) 10)
      (apply * (iota (+ m 1) (+ n 1)))
      (* (partial-factorial m (quotient (+ m n) 2))
         (partial-factorial (quotient (+ m n) 2) n))))
> (let loop ()
  (partial-factorial 1 1000)
  (loop))
*** INTERRUPTED IN ##bignum.*
1> 
> (let loop ()
  (partial-factorial 1 2000)
  (loop))
*** INTERRUPTED IN ##bignum.*
1> 
> (let loop ()  (partial-factorial 1 3000) (loop))
*** INTERRUPTED IN ##bignum.*
1> 
> (let loop ()  (partial-factorial 1 4000) (loop))
*** INTERRUPTED IN ##bignum.*
1> 
> (let loop ()  (partial-factorial 1 5000) (loop))
=================================================================
==321505==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f3f67931820 at pc 0x00000064ba8c bp 0x7ffed4fc0b00 sp 0x7ffed4fc0af0
WRITE of size 8 at 0x7f3f67931820 thread T0
    #0 0x64ba8b in ___H___kernel /home/lucier/programs/gambit/gambit/lib/_kernel.c:11044
    #1 0xb3180f in ___H___num /home/lucier/programs/gambit/gambit/lib/_num.c:101791
    #2 0x58eb1c in ___trampoline /home/lucier/programs/gambit/gambit/lib/setup.c:3035
    #3 0x58fb13 in ___call /home/lucier/programs/gambit/gambit/lib/setup.c:3146
    #4 0x5902c0 in ___run /home/lucier/programs/gambit/gambit/lib/setup.c:3186
    #5 0x598d66 in ___setup /home/lucier/programs/gambit/gambit/lib/setup.c:6170
    #6 0x6290ba in ___main /home/lucier/programs/gambit/gambit/lib/main.c:1222
    #7 0x5d37d3 in ___main_char /home/lucier/programs/gambit/gambit/lib/os_base.c:590
    #8 0x586338 in main /home/lucier/programs/gambit/gambit/gsi/_gsi_.c:15882
    #9 0x7f3f6b3c10b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x569c0d in _start (/home/lucier/programs/gambit/gambit/gsi/gsi+0x569c0d)

0x7f3f67931827 is located 0 bytes to the right of 1048615-byte region [0x7f3f67831800,0x7f3f67931827)
allocated by thread T0 here:
    #0 0x7f3f6c103527 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5d2c85 in ___alloc_mem /home/lucier/programs/gambit/gambit/lib/os_base.c:226
    #2 0x5d2df3 in ___alloc_mem_heap /home/lucier/programs/gambit/gambit/lib/os_base.c:444
    #3 0x598eb6 in alloc_mem_aligned_aux /home/lucier/programs/gambit/gambit/lib/mem.c:563
    #4 0x59905f in alloc_mem_aligned_heap /home/lucier/programs/gambit/gambit/lib/mem.c:611
    #5 0x59a982 in adjust_msections /home/lucier/programs/gambit/gambit/lib/mem.c:967
    #6 0x5a74ee in ___setup_mem_vmstate /home/lucier/programs/gambit/gambit/lib/mem.c:4607
    #7 0x590930 in setup_os_and_mem_vmstate /home/lucier/programs/gambit/gambit/lib/setup.c:4391
    #8 0x5917e0 in ___setup_vmstate /home/lucier/programs/gambit/gambit/lib/setup.c:4596
    #9 0x598a8b in ___setup /home/lucier/programs/gambit/gambit/lib/setup.c:6128
    #10 0x6290ba in ___main /home/lucier/programs/gambit/gambit/lib/main.c:1222
    #11 0x5d37d3 in ___main_char /home/lucier/programs/gambit/gambit/lib/os_base.c:590
    #12 0x586338 in main /home/lucier/programs/gambit/gambit/gsi/_gsi_.c:15882
    #13 0x7f3f6b3c10b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lucier/programs/gambit/gambit/lib/_kernel.c:11044 in ___H___kernel
Shadow bytes around the buggy address:
  0x0fe86cf1e2b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe86cf1e2c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe86cf1e2d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe86cf1e2e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe86cf1e2f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe86cf1e300: 00 00 00 00[07]fa fa fa fa fa fa fa fa fa fa fa
  0x0fe86cf1e310: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe86cf1e320: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe86cf1e330: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe86cf1e340: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe86cf1e350: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==321505==ABORTING
```
That last one failed pretty quickly.
