### ISSUE TITLE
Crash when testing define-library on Ubuntu 22.04

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#821]
Don't know what's happening here:
```
heine:~/programs/gambit/gambit/lib/_define-library> /usr/local/Gambit/bin/gsi -v
v4.9.4-178-g5cd8358f 20230402173703 x86_64-pc-linux-gnu "./configure '--enable-debug'"
heine:~/programs/gambit/gambit/lib/_define-library> gdb /usr/local/Gambit/bin/gsi
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/Gambit/bin/gsi...
(gdb) run test/test.scm
Starting program: /usr/local/Gambit/bin/gsi test/test.scm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
free(): invalid size

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350502208) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) back
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350502208) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350502208) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350502208, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7ccd476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7cb37f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7d146f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7e66b8c "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7d2bd7c in malloc_printerr (str=str@entry=0x7ffff7e6477c "free(): invalid size") at ./malloc/malloc.c:5664
#7  0x00007ffff7d2dad4 in _int_free (av=<optimized out>, p=0x555555f26c50 <cvar>, have_lock=0) at ./malloc/malloc.c:4443
#8  0x00007ffff7d304d3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00005555557fa33a in ___free_mem (ptr=0x555555f26c60 <tempdir_default>) at os_base.c:322
#10 0x00005555557fd524 in ___os_path_tempdir () at os_files.c:1065
#11 0x0000555555815751 in _____kernel_23_31 (___ps=0x5555561f8fc0 <___gstate0>) at _kernel.c:6695
#12 0x0000555555863b98 in ___H___kernel_23_31 (___ps=0x5555561f8fc0 <___gstate0>) at _kernel.c:27178
#13 0x0000555555df800e in ___H__23__23_create_2d_temporary_2d_directory (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:29094
#14 0x0000555555b13dc3 in ___H__23__23_string_2d_concatenate (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105525
#15 0x0000555555b14808 in ___H__23__23_substring_2d_move_21_ (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105684
#16 0x0000555555b13dc3 in ___H__23__23_string_2d_concatenate (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105525
#17 0x0000555555b14808 in ___H__23__23_substring_2d_move_21_ (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105684
#18 0x0000555555b13dc3 in ___H__23__23_string_2d_concatenate (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105525
#19 0x0000555555b143b4 in ___H__23__23_string_2d_append (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105609
#20 0x000055555581eb1c in ___H__23__23_kernel_2d_handlers (___ps=0x5555561f8fc0 <___gstate0>) at _kernel.c:11930
#21 0x0000555555b143b4 in ___H__23__23_string_2d_append (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105609
#22 0x0000555555df800e in ___H__23__23_create_2d_temporary_2d_directory (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:29094
#23 0x0000555555b14808 in ___H__23__23_substring_2d_move_21_ (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105684
#24 0x0000555555b125a4 in ___H__23__23_substring (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105163
#25 0x0000555555df4f44 in ___H__23__23_path_2d_strip_2d_directory (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:28413
#26 0x0000555555df463c in ___H__23__23_path_2d_directory_2d_end (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:28291
#27 0x0000555555dec7c0 in ___H__23__23_path_2d_volume_2d_end_2d_using_2d_dir_2d_sep (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:26290
#28 0x0000555555df463c in ___H__23__23_path_2d_directory_2d_end (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:28291
#29 0x0000555555dce52b in ___H__23__23_identity (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:19349
#30 0x0000555555b454b3 in ___H__23__23_make_2d_parameter (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:117521
#31 0x0000555555e21ba1 in ___H__23__23_dynamic_2d_ref (___ps=0x5555561f8fc0 <___gstate0>) at _thread.c:9993
#32 0x0000555555b454b3 in ___H__23__23_make_2d_parameter (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:117521
#33 0x0000555555df463c in ___H__23__23_path_2d_directory_2d_end (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:28291
#34 0x0000555555df4f44 in ___H__23__23_path_2d_strip_2d_directory (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:28413
#35 0x0000555555df800e in ___H__23__23_create_2d_temporary_2d_directory (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:29094
#36 0x0000555555df282d in ___H__23__23_path_2d_normalize (___ps=0x5555561f8fc0 <___gstate0>) at _nonstd.c:27872
#37 0x0000555555b13dc3 in ___H__23__23_string_2d_concatenate (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105525
#38 0x0000555555b14808 in ___H__23__23_substring_2d_move_21_ (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105684
#39 0x0000555555b13dc3 in ___H__23__23_string_2d_concatenate (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105525
#40 0x0000555555b14808 in ___H__23__23_substring_2d_move_21_ (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105684
#41 0x0000555555b13dc3 in ___H__23__23_string_2d_concatenate (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105525
#42 0x0000555555b143b4 in ___H__23__23_string_2d_append (___ps=0x5555561f8fc0 <___gstate0>) at _std.c:105609
#43 0x00005555557e336c in ___trampoline (___ps=0x5555561f8fc0 <___gstate0>) at setup.c:3176
#44 0x00005555557e3736 in ___call (nargs=0, proc=93825003628369, stack_marker=93825005591841) at setup.c:3287
#45 0x00005555557e392d in ___run (thunk=93825003628369) at setup.c:3327
#46 0x00005555557e62a5 in ___setup (setup_params=0x7fffffffe000) at setup.c:6333
#47 0x0000555555813010 in ___main (linker=0x5555557e0799 <___LNK___gsi__>) at main.c:1222
#48 0x00005555557fa63e in ___main_char (argc=2, argv=0x7fffffffe258, linker=0x5555557e0799 <___LNK___gsi__>, script_line=0x0)
    at os_base.c:590
#49 0x00005555557e07db in main (argc=2, argv=0x7fffffffe258) at _gsi_.c:16119
(gdb) 
```

**Comment by feeley** [comment]
Thanks! This is an actual bug (attempt to free a static string).
