### ISSUE TITLE
"make ut-js" gets stuck in 05-serdes/serdes.scm

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#870]
Things get stuck here:
```
heine:~/programs/gambit/gambit> make ut-js
<lots of stuff elided>
LD_LIBRARY_PATH=../lib:../gsi:../gsc:/usr/local/libimobiledevice/lib:/usr/local/Gambit/current/lib:/usr/local/netpbm10/lib:/usr/local/chibi/lib: ../gsi/gsi -:tl,~~bin=../bin,~~lib=../lib,~~include=../include -f ./run-unit-tests.scm -js -gsc
[193|  0]  66% ##########...... 237.7s 05-serdes/serdes.scm
```

**Comment by gambiteer** [comment]
The following also hang:
```
[205|  1]  71% ###########..... 264.6s 06-thread/thread_interrupt.scm
[205|  1]  71% ###########..... 262.1s 06-thread/thread_join.scm
[209|  2]  73% ###########..... 270.3s 06-thread/thread_state.scm
[242|  3]  85% #############... 341.3s 11-network/udp_close.scm
[242|  3]  85% #############... 328.9s 11-network/udp_destination_set.scm
[242|  3]  86% #############... 349.9s 11-network/udp_io.scm
[242|  3]  86% #############... 351.0s 11-network/udp_open.scm
[242|  3]  86% #############... 351.2s 11-network/udp_socket_info.scm
[242|  3]  87% #############... 332.3s 11-network/udp_timeout.scm
```
and after eliminating the tests that hang we get
```
LD_LIBRARY_PATH=../lib:../gsi:../gsc:/usr/local/libimobiledevice/lib:/usr/local/Gambit/current/lib:/usr/local/netpbm10/lib:/usr/local/chibi/lib: ../gsi/gsi -:tl,~~bin=../bin,~~lib=../lib,~~include=../include -f ./run-unit-tests.scm -js -gsc
[204|  0]  73% ###########..... 241.0s 06-thread/thread.scm
*** FAILED 06-thread/thread.scm WITH EXIT CODE HI=1 LO=0
"unit-tests/06-thread/thread.scm"@20.1-20.21: FAILED (check-equal? var 1) GOT 0
[209|  1]  75% ############.... 253.9s 06-thread/thread_start.scm
*** FAILED 06-thread/thread_start.scm WITH EXIT CODE HI=1 LO=0
"unit-tests/06-thread/thread_start.scm"@32.1-32.21: FAILED (check-equal? var 1) GOT 0
[239|  2]  86% #############... 318.0s 10-tables/table-copy.scm
*** FAILED 10-tables/table-copy.scm WITH EXIT CODE HI=1 LO=0
"unit-tests/10-tables/table-copy.scm"@43.6-43.34: FAILED (check-true (equal? t copy)) GOT #!void
"unit-tests/10-tables/table-copy.scm"@43.6-43.34: FAILED (check-true (equal? t copy)) GOT #!void
"unit-tests/10-tables/table-copy.scm"@43.6-43.34: FAILED (check-true (equal? t copy)) GOT #!void
"unit-tests/10-tables/table-copy.scm"@43.6-43.34: FAILED (check-true (equal? t copy)) GOT #!void
[242|  3]  87% ##############.. 322.4s 12-os/command_line.scm
*** FAILED 12-os/command_line.scm WITH EXIT CODE HI=1 LO=0
"unit-tests/12-os/command_line.scm"@3.1-3.36: FAILED (check-equal? (command-line) '("")) GOT ("/home/lucier/programs/gambit/gambit/tests/_test.bat")
[242|  4]  88% ##############.. 323.5s 12-os/command_name.scm
*** FAILED 12-os/command_name.scm WITH EXIT CODE HI=1 LO=0
"unit-tests/12-os/command_name.scm"@3.1-3.33: FAILED (check-equal? (command-name) #f) GOT "_test"
[251|  5]  91% ##############.. 336.5s 13-modules/prim_filesystem.scm
*** FAILED 13-modules/prim_filesystem.scm WITH EXIT CODE HI=1 LO=0
unimplemented ##os-copy-file called with src-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and dest-path=
/home/lucier/programs/gambit/gambit/tests/test_file2.txt
unimplemented ##os-create-fifo called with path=
/home/lucier/programs/gambit/gambit/tests/test_fifo
and permissions=
438
unimplemented ##os-create-link called with old-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and new-path=
/home/lucier/programs/gambit/gambit/tests/test_link
unimplemented ##os-create-symbolic-link called with old-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and new-path=
/home/lucier/programs/gambit/gambit/tests/test_link
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.995
and m-time=
1701826974.995
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.012
and m-time=
1701826974.012
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.017
and m-time=
1701826973.017
unimplemented ##os-copy-file called with src-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and dest-path=
/home/lucier/programs/gambit/gambit/tests/test_file2.txt
unimplemented ##os-create-fifo called with path=
/home/lucier/programs/gambit/gambit/tests/test_fifo
and permissions=
438
unimplemented ##os-create-link called with old-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and new-path=
/home/lucier/programs/gambit/gambit/tests/test_link
unimplemented ##os-create-symbolic-link called with old-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and new-path=
/home/lucier/programs/gambit/gambit/tests/test_link
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826975.077
and m-time=
1701826975.077
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.081
and m-time=
1701826974.081
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.085
and m-time=
1701826973.085
unimplemented ##os-copy-file called with src-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and dest-path=
/home/lucier/programs/gambit/gambit/tests/test_file2.txt
unimplemented ##os-create-fifo called with path=
/home/lucier/programs/gambit/gambit/tests/test_fifo
and permissions=
438
unimplemented ##os-create-link called with old-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and new-path=
/home/lucier/programs/gambit/gambit/tests/test_link
unimplemented ##os-create-symbolic-link called with old-path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and new-path=
/home/lucier/programs/gambit/gambit/tests/test_link
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826975.122
and m-time=
1701826975.122
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.126
and m-time=
1701826974.126
unimplemented ##os-file-times-set! called with path=
/home/lucier/programs/gambit/gambit/tests/test_file.txt
and a-time=
1701826974.129
and m-time=
1701826973.129
(let ((x "test_file.txt") (y "test_file2.txt")) (##with-output-to-file x ##list) (copy-file x y) (delete-file x) (delete-file y)) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #2> but expected #<os-exception #3>
(and (not ##windows?) (let ((x "test_fifo")) (create-fifo x) (delete-file x))) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #4> but expected #<os-exception #5>
(and (not ##windows?) (let ((x "test_file.txt") (y "test_link")) (##with-output-to-file x ##list) (create-link x y) (delete-file x) (delete-file y))) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #6> but expected #<os-exception #7>
(and (not ##windows?) (let ((x "test_file.txt") (y "test_link")) (##with-output-to-file x ##list) (create-symbolic-link x y) (delete-file x) (delete-file y))) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #8> but expected #<os-exception #9>
(let ((x "test_file.txt")) (##with-output-to-file x ##list) (file-last-access-and-modification-times-set! x) (delete-file x)) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #10> but expected #<os-exception #11>
(let ((x "test_file.txt")) (##with-output-to-file x ##list) (file-last-access-and-modification-times-set! x -1) (delete-file x)) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #12> but expected #<os-exception #13>
(let ((x "test_file.txt")) (##with-output-to-file x ##list) (file-last-access-and-modification-times-set! x -1 -2) (delete-file x)) in (include "~~lib/gambit/prim/filesystem#.scm") returned #<os-exception #14> but expected #<os-exception #15>
(let ((x "test_file.txt") (y "test_file2.txt")) (##with-output-to-file x ##list) (copy-file x y) (delete-file x) (delete-file y)) in (namespace ("##")) returned #<os-exception #16> but expected #<os-exception #3>
(and (not ##windows?) (let ((x "test_fifo")) (create-fifo x) (delete-file x))) in (namespace ("##")) returned #<os-exception #17> but expected #<os-exception #5>
(and (not ##windows?) (let ((x "test_file.txt") (y "test_link")) (##with-output-to-file x ##list) (create-link x y) (delete-file x) (delete-file y))) in (namespace ("##")) returned #<os-exception #18> but expected #<os-exception #7>
(and (not ##windows?) (let ((x "test_file.txt") (y "test_link")) (##with-output-to-file x ##list) (create-symbolic-link x y) (delete-file x) (delete-file y))) in (namespace ("##")) returned #<os-exception #19> but expected #<os-exception #9>
(let ((x "test_file.txt")) (##with-output-to-file x ##list) (file-last-access-and-modification-times-set! x) (delete-file x)) in (namespace ("##")) returned #<os-exception #20> but expected #<os-exception #11>
(let ((x "test_file.txt")) (##with-output-to-file x ##list) (file-last-access-and-modification-times-set! x -1) (delete-file x)) in (namespace ("##")) returned #<os-exception #21> but expected #<os-exception #13>
(let ((x "test_file.txt")) (##with-output-to-file x ##list) (file-last-access-and-modification-times-set! x -1 -2) (delete-file x)) in (namespace ("##")) returned #<os-exception #22> but expected #<os-exception #15>
[255|  6]  93% ##############.. 346.7s 13-modules/prim_misc.scm
*** FAILED 13-modules/prim_misc.scm WITH EXIT CODE HI=1 LO=0
"##" namespace:
<lot of stuff removed>
empty namespace:
<lot of stuff removed>
"_gambit#" namespace:
  ||
"prim_misc#" namespace:
  ||
"syn#" namespace:
  apply-rules, compile-pattern, compile-template, cp, cp-list, ct, ct-list,
  define-syntax-form-transformer, et, expand-template, fail?, match-fail,
  match-pattern, match-success?, mp, mp-list, pattern-ellipsis?, pattern-pvar?,
  pvar-id, syntax-case-form-transformer, syntax-form-transformer,
  syntax-rules->crules, syntax-rules-form-transformer, template-ellipsis?,
  template-pvar?
empty namespace:
<lot of stuff removed>
"##" namespace:
<lot of stuff removed>
"_gambit#" namespace:
  ||
"prim_misc#" namespace:
  ||
"syn#" namespace:
  apply-rules, compile-pattern, compile-template, cp, cp-list, ct, ct-list,
  define-syntax-form-transformer, et, expand-template, fail?, match-fail,
  match-pattern, match-success?, mp, mp-list, pattern-ellipsis?, pattern-pvar?,
  pvar-id, syntax-case-form-transformer, syntax-form-transformer,
  syntax-rules->crules, syntax-rules-form-transformer, template-ellipsis?,
  template-pvar?
empty namespace:
<lot of stuff removed>
(equal?-hash 2) in (include "~~lib/gambit/prim/misc#.scm") returned #<nonprocedure-operator-exception #3> but expected #<nonprocedure-operator-exception #4>
(equal?-hash 2) in (namespace ("##")) returned #<nonprocedure-operator-exception #5> but expected #<nonprocedure-operator-exception #4>
[256|  7]  94% ###############. 353.7s 13-modules/prim_os.scm
*** FAILED 13-modules/prim_os.scm WITH EXIT CODE HI=1 LO=0
unimplemented ##os-environ called
unimplemented ##os-environ called
unimplemented ##os-environ called
unimplemented ##os-environ called
unimplemented ##os-environ called
unimplemented ##os-environ called
(shell-command "type #.scm") in (include "~~lib/gambit/prim/os#.scm") returned #<os-exception #2> but expected #<os-exception #3>
(shell-command "type #.scm" #t) in (include "~~lib/gambit/prim/os#.scm") returned #<os-exception #4> but expected #<os-exception #5>
(shell-command "type #.scm") in (namespace ("##")) returned #<os-exception #6> but expected #<os-exception #3>
(shell-command "type #.scm" #t) in (namespace ("##")) returned #<os-exception #7> but expected #<os-exception #5>
[256|  8]  94% ###############. 354.9s 13-modules/prim_port.scm(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:2224579) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.

*** FAILED 13-modules/prim_port.scm WITH EXIT CODE HI=1 LO=0
(call-with-input-process (##list path: "sort" arguments: (##list ##_input-file)) ##read-line) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #2> but expected #<os-exception #3>
(call-with-output-process "sort" ##newline) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #4> but expected #<os-exception #5>
(let ((x ##_temp-file)) (##with-output-to-file x ##newline) (let ((result (##call-with-input-file x (lambda (p) (input-port-byte-position p))))) (##delete-file x) result)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #6> but expected #<os-exception #7>
(let ((x ##_temp-file)) (##with-output-to-file x ##newline) (let ((result (##call-with-input-file x (lambda (p) (input-port-byte-position p 1))))) (##delete-file x) result)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #8> but expected #<os-exception #9>
(let ((x ##_temp-file)) (##with-output-to-file x ##newline) (let ((result (##call-with-input-file x (lambda (p) (input-port-byte-position p 0 2))))) (##delete-file x) result)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #10> but expected #<os-exception #11>
(let* ((p (open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##read-line p))) (##close-input-port p) result) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #12> but expected #<os-exception #13>
(let ((p (open-output-process "sort"))) (##close-output-port p)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #14> but expected #<os-exception #15>
(let ((x ##_temp-file)) (let ((result (##call-with-output-file x (lambda (p) (output-port-byte-position p))))) (##delete-file x) result)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #16> but expected #<os-exception #17>
(let ((x ##_temp-file)) (let ((result (##call-with-output-file x (lambda (p) (output-port-byte-position p 1))))) (##delete-file x) result)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #18> but expected #<os-exception #19>
(let ((x ##_temp-file)) (let ((result (##call-with-output-file x (lambda (p) (output-port-byte-position p 0 2))))) (##delete-file x) result)) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #20> but expected #<os-exception #21>
(port-settings-set! (##current-input-port) '()) in (include "~~lib/gambit/prim/port#.scm") returned (#<os-exception #22>) but expected (#<os-exception #23>)
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-pid p)))) (##close-input-port p) result) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #24> but expected #<os-exception #25>
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-status p)))) (##close-input-port p) result) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #26> but expected #<os-exception #27>
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-status p 10)))) (##close-input-port p) result) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #28> but expected #<os-exception #29>
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-status p 10 42)))) (##close-input-port p) result) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #30> but expected #<os-exception #31>
(with-input-from-process (##list path: "sort" arguments: (##list ##_input-file)) ##read-line) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #32> but expected #<os-exception #33>
(with-output-to-process "sort" ##newline) in (include "~~lib/gambit/prim/port#.scm") returned #<os-exception #34> but expected #<os-exception #35>
(call-with-input-process (##list path: "sort" arguments: (##list ##_input-file)) ##read-line) in (namespace ("##")) returned #<os-exception #36> but expected #<os-exception #3>
(call-with-output-process "sort" ##newline) in (namespace ("##")) returned #<os-exception #37> but expected #<os-exception #5>
(let ((x ##_temp-file)) (##with-output-to-file x ##newline) (let ((result (##call-with-input-file x (lambda (p) (input-port-byte-position p))))) (##delete-file x) result)) in (namespace ("##")) returned #<os-exception #38> but expected #<os-exception #7>
(let ((x ##_temp-file)) (##with-output-to-file x ##newline) (let ((result (##call-with-input-file x (lambda (p) (input-port-byte-position p 1))))) (##delete-file x) result)) in (namespace ("##")) returned #<os-exception #39> but expected #<os-exception #9>
(let ((x ##_temp-file)) (##with-output-to-file x ##newline) (let ((result (##call-with-input-file x (lambda (p) (input-port-byte-position p 0 2))))) (##delete-file x) result)) in (namespace ("##")) returned #<os-exception #40> but expected #<os-exception #11>
(let* ((p (open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##read-line p))) (##close-input-port p) result) in (namespace ("##")) returned #<os-exception #41> but expected #<os-exception #13>
(let ((p (open-output-process "sort"))) (##close-output-port p)) in (namespace ("##")) returned #<os-exception #42> but expected #<os-exception #15>
(let ((x ##_temp-file)) (let ((result (##call-with-output-file x (lambda (p) (output-port-byte-position p))))) (##delete-file x) result)) in (namespace ("##")) returned #<os-exception #43> but expected #<os-exception #17>
(let ((x ##_temp-file)) (let ((result (##call-with-output-file x (lambda (p) (output-port-byte-position p 1))))) (##delete-file x) result)) in (namespace ("##")) returned #<os-exception #44> but expected #<os-exception #19>
(let ((x ##_temp-file)) (let ((result (##call-with-output-file x (lambda (p) (output-port-byte-position p 0 2))))) (##delete-file x) result)) in (namespace ("##")) returned #<os-exception #45> but expected #<os-exception #21>
(port-settings-set! (##current-input-port) '()) in (namespace ("##")) returned (#<os-exception #46>) but expected (#<os-exception #23>)
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-pid p)))) (##close-input-port p) result) in (namespace ("##")) returned #<os-exception #47> but expected #<os-exception #25>
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-status p)))) (##close-input-port p) result) in (namespace ("##")) returned #<os-exception #48> but expected #<os-exception #27>
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-status p 10)))) (##close-input-port p) result) in (namespace ("##")) returned #<os-exception #49> but expected #<os-exception #29>
(let* ((p (##open-input-process (##list path: "sort" arguments: (##list ##_input-file)))) (result (##number? (process-status p 10 42)))) (##close-input-port p) result) in (namespace ("##")) returned #<os-exception #50> but expected #<os-exception #31>
(with-input-from-process (##list path: "sort" arguments: (##list ##_input-file)) ##read-line) in (namespace ("##")) returned #<os-exception #51> but expected #<os-exception #33>
(with-output-to-process "sort" ##newline) in (namespace ("##")) returned #<os-exception #52> but expected #<os-exception #35>
[262|  9]  97% ###############. 368.4s 13-modules/prim_table.scm
*** FAILED 13-modules/prim_table.scm WITH EXIT CODE HI=1 LO=0
(table-merge (list->table '((a . 1))) (list->table '((a . 2)))) in (include "~~lib/gambit/prim/table#.scm") returned #<nonprocedure-operator-exception #2> but expected #<nonprocedure-operator-exception #3>
(table-merge (list->table '((a . 1))) (list->table '((a . 2))) #t) in (include "~~lib/gambit/prim/table#.scm") returned #<nonprocedure-operator-exception #4> but expected #<nonprocedure-operator-exception #5>
(let ((x (list->table '((a . 1))))) (table-merge! x (list->table '((a . 2)))) x) in (include "~~lib/gambit/prim/table#.scm") returned #<nonprocedure-operator-exception #6> but expected #<nonprocedure-operator-exception #7>
(let ((x (list->table '((a . 1))))) (table-merge! x (list->table '((a . 2))) #t) x) in (include "~~lib/gambit/prim/table#.scm") returned #<nonprocedure-operator-exception #8> but expected #<nonprocedure-operator-exception #9>
(table-merge (list->table '((a . 1))) (list->table '((a . 2)))) in (namespace ("##")) returned #<nonprocedure-operator-exception #10> but expected #<nonprocedure-operator-exception #3>
(table-merge (list->table '((a . 1))) (list->table '((a . 2))) #t) in (namespace ("##")) returned #<nonprocedure-operator-exception #11> but expected #<nonprocedure-operator-exception #5>
(let ((x (list->table '((a . 1))))) (table-merge! x (list->table '((a . 2)))) x) in (namespace ("##")) returned #<nonprocedure-operator-exception #12> but expected #<nonprocedure-operator-exception #7>
(let ((x (list->table '((a . 1))))) (table-merge! x (list->table '((a . 2))) #t) x) in (namespace ("##")) returned #<nonprocedure-operator-exception #13> but expected #<nonprocedure-operator-exception #9>
[267| 10]  99% ###############. 376.8s 13-modules/prim_will.scm/home/lucier/programs/gambit/gambit/tests/_test.bat:930
pc = pc();
     ^

TypeError: pc is not a function
    at _trampoline (/home/lucier/programs/gambit/gambit/tests/_test.bat:930:6)
    at _call_start (/home/lucier/programs/gambit/gambit/tests/_test.bat:1041:1)
    at _program_start (/home/lucier/programs/gambit/gambit/tests/_test.bat:1767:1)
    at _all_modules_registered (/home/lucier/programs/gambit/gambit/tests/_test.bat:1810:1)
    at _module_register (/home/lucier/programs/gambit/gambit/tests/_test.bat:1944:1)
    at Object.<anonymous> (/home/lucier/programs/gambit/gambit/tests/_test.bat:501708:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

*** FAILED 13-modules/prim_will.scm WITH EXIT CODE HI=1 LO=0
[268| 11] 100% ################ 379.3s
FAILED 11 UNIT TESTS OUT OF 279 (3.9%)
make[1]: *** [makefile:192: ut-js] Error 1
make[1]: Leaving directory '/home/lucier/programs/gambit/gambit/tests'
make: *** [makefile:211: ut-js] Error 2
```

**Comment by gambiteer** [comment]
`serdes.scm` still hangs.

**Comment by gambiteer** [comment]
Would it be easy to set up each test to automatically fail after 60 seconds of execution time?
